name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag samueladekunle/simplenext-dev:latest

      - name: Run the jest tests
        run: docker run samueladekunle/simplenext-dev:latest npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag samueladekunle/simplenext-dev:latest

      - name: Run the jest tests
        run: docker run samueladekunle/simplenext-dev:latest npm run test -- --coverage

  publish:
    runs-on: ubuntu-latest
    needs: [ lint, test ]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Configure gcloud authentication
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799494570525/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'docker-image-service-account@docker-course-352310.iam.gserviceaccount.com'

      - name: 'Set up cloud sdk'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: docker-course-352310

      - name: Configure docker authentication
        run: echo "y" | gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build images
        run: docker build --file Dockerfile.prod -t europe-west2-docker.pkg.dev/docker-course-352310/docker-repo/simplenext:latest .

      - name: Publish images
        run: docker push europe-west2-docker.pkg.dev/docker-course-352310/docker-repo/simplenext:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ publish ]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Configure gcloud authentication
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799494570525/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'docker-image-service-account@docker-course-352310.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          region: europe-west2
          metadata: "service.yml"

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'